### ISSUE TITLE
Dear PyGui showcase app

### ISSUE THREAD

**Issue by bandit-masked** [retifrav/tap-adql-sandbox#18]
Hey, it looks like you may have an interesting app for the [Dear PyGui showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase). If you would like your app to be featured there, could you make a screenshot or GIF so that we can add it there?

**Comment by retifrav** [comment]
Sure, it's quite flattering, thanks!

You can take the [main screenshot](https://raw.githubusercontent.com/retifrav/tap-adql-sandbox/master/misc/screenshot-main-macos.png) from README, and here's also a video:

https://user-images.githubusercontent.com/6904927/154363460-7d15a0e5-aaec-4021-9ebf-3a3e4bf9b71f.mp4

It's of higher quality (*and smaller size*) than a GIF, and GitHub does allow inserting videos on pages, but if you need exactly GIF, then here's this video converted into one:

![tap-adql-sandbox](https://user-images.githubusercontent.com/6904927/154363686-151ec21e-dbc8-440c-be9c-6a787853fa3a.gif)

**Comment by bandit-masked** [comment]
You are welcome! Thank you for the video and GIF. I will see which I can best use. I believe that MP4 is not supported on the GitHub wiki. If not, I will use your GIF or try to convert the MP4 with [EZgif](https://ezgif.com/video-to-gif), my favourite GIF converter so far as it provides some control over output quality and size.

I like how your app shows different aspects of Dear PyGui. It looks simple, yet polished. It's a very specific tool and for that it works well. I believe many developers would build similar tools, so it's beneficial to show various possibilities with Dear PyGui. And people could also review your code to learn how you have solved certain challenges.

Are you on the Dear PyGui Discord, by the way? 

Please keep us updated if you further improve your app or create a new one with Dear PyGui! You can do that by posting on Discord or by filing an issue on [Dear PyGui's GitHub](https://github.com/hoffstadt/DearPyGui).

**Comment by bandit-masked** [comment]
Also, could you write a few more lines about the app as to what it does?  Who would use this and why?

ADQL = Astronomical Data Query Language?  How is that different from SQL?

And what does TAP interface stand for?

**Comment by retifrav** [comment]
TAP stands for [Table Access Protocol](https://www.ivoa.net/documents/TAP/), it's a way to expose/query data from a database.

Correct, ADQL stands for [Astronomical Data Query Language](https://www.ivoa.net/documents/ADQL/20180112/PR-ADQL-2.1-20180112.html) and it is very similar to SQL, just with extended functionality for performing various operations on the data (*such as [geometrical functions](https://www.ivoa.net/documents/ADQL/20180112/PR-ADQL-2.1-20180112.html#tth_sEc4.2)*).

The application description would be almost the same as in the first paragraph of the README:

> A sandbox application for executing ADQL queries via TAP interface of various data sources, such as astronomical databases. Essentially, it's just a GUI for [PyVO](https://pypi.org/project/pyvo/). You can use it to try out your queries in a convenient manner before adding them to your code.

So the idea is that one can quickly run and test his ADQL queries using this application and then add the final query to his application/notebook. I'd expect this to be of interest for planetary scientists / astronomers, as so far I saw mostly astronomical databases exposing their data via TAP interface.

I was thinking about joining the Discord chat, but it's hard to keep up with so many chats, so I haven't yet.

Sure thing, I'll let you know if there is anything new about this application or if I'll have a new one. I most definitively will have more questions/issues to post in the Dear PyGui repository.

**Comment by bandit-masked** [comment]
Ok, thanks for the explanation! Your GIF looks fine by the way, please ignore my mumbling about conversion :-)

Did you share your application on r/astronomy or other social networks? I'm sure other would be interested in using it!

Looking forward to updates and/or new applications!

**Comment by retifrav** [comment]
No, I haven't shared it anywhere yet, so far it was just me and my colleagues who've been using it.
But as almost all the planned/main functionality is implemented now, I'll probably post some announces in different places.
Thank you!

**Comment by bandit-masked** [comment]
It's up on the showcase. Thanks for your replies. It's been really helpful and insightful!
